#!/bin/sh

brew install cmake ninja

export CC=$(which clang)
export CXX=$(which clang++)

git clone https://github.com/yrnkrn/zapcc.git llvm
mkdir build
cd build
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_WARNINGS=OFF ../llvm
ninja
